package com.artvantage.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

@Embeddable
public class UserPurchaseId implements Serializable {

    @Column(name = "content_id")
    private String contentId;

    @Column(name = "user_id")
    private String userId;

    // Getters and setters for contentId and userId
    // Equals and hashCode methods (implementations can be generated by your IDE)
}
